repos:
  - repo: local
    hooks:
      - id: make-fmt
        name: Run make fmt
        entry: make fmt
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true  # Run even if no files are staged
      - id: make-lint
        name: Run make lint
        entry: make lint
        language: system
        files: \.py$
        pass_filenames: false
        always_run: true  
      - id: make-clean
        name: Run make clean
        entry: make clean
        language: system
        files: ''
        pass_filenames: false
        always_run: true 

  - repo: https://github.com/pycqa/doc8
    rev: 0.11.2
    hooks:
      - id: doc8
        args: [--max-line-length=120]

  - repo: https://github.com/myint/rstcheck
    rev: v6.2.0
    hooks:
      - id: rstcheck


  - repo: https://github.com/dzhu/rstfmt
    rev: v0.0.14
    hooks:
      - id: rstfmt
        args: ["-w", "120"]

