# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install project
        run: make install
      - name: Run linter
        run: make lint

  build:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clear existing cache
        run: |
          rm -rf ~/.cache/pip
          rm -rf ./.gradle/caches/
          rm -rf ~/.m2/repository/

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # we will use length 79 instead
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
      - name: Test with pytest and calculate coverage
        run: |
          pytest --cov-report "xml:coverage.xml"  --cov=.
      - name: Create Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

  tests_linux:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: make install
      - name: Run tests
        run: make test
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5
        # with:
        #   fail_ci_if_error: true

  tests_mac:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: make install
      - name: Run tests
        run: make test

  tests_win:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pip
        run: pip install --user pip
      - name: Upgrading Pip
        run: python.exe -m pip install --upgrade pip
      - name: Install project
        run: pip install -e .[test]
      - name: run tests
        run: pytest -s -vvvv -l --tb=long tests
